### ISSUE TITLE
Option to bind to different interface

### ISSUE THREAD

**Issue by tleyden** [davecheney/gcvis#16]
Currently it's [harcoded](https://github.com/davecheney/gcvis/blob/master/main.go#L33
) to bind to localhost:

```
listener, err := net.Listen("tcp4", "127.0.0.1:0")
```

It would be nice if it were possible to pass in a different interface as an option.  This will be useful for being able to connect from a local workstation to gcvis running on remote servers.

**Comment by davecheney** [comment]
@tleyden i'd gladly accept a pull request if you wanted to send one.
