### ISSUE TITLE
Add travis CI

### ISSUE THREAD

**Issue by kouno** [davecheney/gcvis#20]
@davecheney I'm pretty sure you are the only one with the necessary permissions to do so. :wink:

**Comment by davecheney** [comment]
I've never used Travis CI before, how do I do it, is it a dotfile in the root of a repo and some account somewhere ?

**Comment by kouno** [comment]
> I've never used Travis CI before, how do I do it, is it a dotfile in the root of a repo and some account somewhere ?

Indeed. Just follow https://travis-ci.org/getting_started.

I would have done it, but since you own `davecheney/gcvis` you are the only one who has the fancy switch button for the project.

As for the `.travis.yml` file, I would advise testing against 1.3, 1.4 and 1.5 with:
```yaml
language: go
go:
  - 1.3
  - 1.4
  - 1.5
```

And maybe `tip` if that counts as 1.6.

See http://docs.travis-ci.com/user/languages/go/ for other options.

**Comment by davecheney** [comment]
Done.
